import type { Instant, Track } from "../domain/types";

type SeedTrack = Omit<Track, "createdAt" | "updatedAt">;

const TRACKS: SeedTrack[] = [
  {
    id: "english",
    slug: "english",
    name: "English",
    description: "Career communication practice",
    icon: "Languages",
    color: "#2563eb",
    status: "active",
    sortOrder: 10,
    defaultPoints: 2,
    weeklyTarget: 5,
    minimumAction: "Speak or write English for 3 minutes",
    normalAction: "Practice English for 20 minutes",
    strongAction: "Record or write a full technical explanation",
    endOfYearGoal: "Complete 100+ English speaking, writing, or reflection reps.",
    countsTowardNoZero: true,
  },
  {
    id: "korean",
    slug: "korean",
    name: "Korean",
    description: "Fun language learning",
    icon: "BookOpen",
    color: "#db2777",
    status: "active",
    sortOrder: 20,
    defaultPoints: 1,
    weeklyTarget: 3,
    minimumAction: "Review 5 Korean words",
    normalAction: "Complete 15 minutes of Korean learning",
    strongAction: "Complete a lesson and listening session",
    endOfYearGoal: "Complete 50+ enjoyable Korean learning sessions.",
    countsTowardNoZero: true,
  },
  {
    id: "vinance",
    slug: "vinance",
    name: "Vinance",
    description: "Personal product building",
    icon: "Blocks",
    color: "#0f766e",
    status: "active",
    sortOrder: 30,
    defaultPoints: 3,
    weeklyTarget: 5,
    minimumAction: "Work on Vinance for 10 minutes",
    normalAction: "Complete one focused build session",
    strongAction: "Ship or complete a meaningful feature/task",
    endOfYearGoal: "Make regular, documented progress on the Vinance product.",
    countsTowardNoZero: true,
  },
  {
    id: "devlog",
    slug: "devlog",
    name: "Devlog",
    description: "Progress writing and reflection",
    icon: "NotebookPen",
    color: "#7c3aed",
    status: "active",
    sortOrder: 40,
    defaultPoints: 2,
    weeklyTarget: 2,
    minimumAction: "Write 2 devlog bullets",
    normalAction: "Draft one section",
    strongAction: "Publish or complete a devlog",
    endOfYearGoal: "Write 20+ devlogs or weekly progress notes.",
    countsTowardNoZero: true,
  },
  {
    id: "taste",
    slug: "taste",
    name: "Taste-Building",
    description: "Improve judgment through observation",
    icon: "Sparkles",
    color: "#d97706",
    status: "active",
    sortOrder: 50,
    defaultPoints: 1,
    weeklyTarget: 2,
    minimumAction: "Capture 1 taste observation",
    normalAction: "Write a structured taste note",
    strongAction: "Analyze something deeply and extract lessons",
    endOfYearGoal: "Create 20+ taste notes with useful judgments and lessons.",
    countsTowardNoZero: true,
  },
  {
    id: "conversation",
    slug: "conversation",
    name: "Conversation",
    description: "Practice intentional conversation",
    icon: "MessagesSquare",
    color: "#c2410c",
    status: "active",
    sortOrder: 60,
    defaultPoints: 1,
    weeklyTarget: 2,
    minimumAction: "Ask 1 better question",
    normalAction: "Reflect on one conversation",
    strongAction: "Have an intentional conversation and follow up",
    endOfYearGoal: "Complete 20+ intentional conversation reps.",
    countsTowardNoZero: true,
  },
];

export function createSeedTracks(timestamp: Instant): Track[] {
  return TRACKS.map((track) => ({
    ...track,
    createdAt: timestamp,
    updatedAt: timestamp,
  }));
}
